import pence from "../presidential-candidates/candidate-imgs/pence.png";
import hutchinson from "../presidential-candidates/candidate-imgs/hutchinson.png";
import binkley from "../presidential-candidates/candidate-imgs/binkley.png";
import hurd from "../presidential-candidates/candidate-imgs/hurd.png";
import kennedyJr from "../presidential-candidates/candidate-imgs/kennedy-jr.png";
import tScott from "../presidential-candidates/candidate-imgs/t_scott.png";
import christie from "../presidential-candidates/candidate-imgs/christie.png";
import burgum from "../presidential-candidates/candidate-imgs/burgum.png";
import trump from "../presidential-candidates/candidate-imgs/trump.png";
import ramaswamy from "../presidential-candidates/candidate-imgs/ramaswamy.png";
import haley from "../presidential-candidates/candidate-imgs/haley.png";
import west from "../presidential-candidates/candidate-imgs/west.png";
import elder from "../presidential-candidates/candidate-imgs/elder.png";
import desantis from "../presidential-candidates/candidate-imgs/desantis.png";
import biden from "../presidential-candidates/candidate-imgs/biden.png";
import williamson from "../presidential-candidates/candidate-imgs/williamson.png";
import johnson from "../presidential-candidates/candidate-imgs/johnson.png";

export const candidates = {
  biden: {
    name: "Joseph R. Biden Jr.",
    desc: "Current President",
    img: biden,
    party: "Democrat",
    subheading: "46th President of the United States",
    website: "https://www.whitehouse.gov/",
    birthday: "November 20, 1942",
    about: [
      "Joseph Robinette Biden Jr. is the 46th President of the United States, serving as the nation's leader since January 20, 2021. Born on November 20, 1942, in Scranton, Pennsylvania, Biden has had a long and distinguished career in American politics.",
      "Before becoming president, Biden served as Vice President under President Barack Obama from 2009 to 2017. During his tenure, he played key roles in several policy initiatives, including the Affordable Care Act (Obamacare) and efforts to combat climate change.",
      "Throughout his political career, Biden has been known for his commitment to issues such as healthcare reform, economic recovery, and foreign policy. His presidency has been marked by efforts to address the COVID-19 pandemic, promote infrastructure investment, and tackle climate change.",
      "Joseph R. Biden Jr. is a member of the Democratic Party and has a long history of public service, making him one of the most experienced individuals to hold the office of the President of the United States.",
      "As with any political figure, opinions about President Biden are divided, and his policies and decisions continue to be the subject of debate and discussion in American politics.",
    ],
    transcripts: [
      {
        url: "https://www.rev.com/blog/transcripts/president-biden-delivers-remarks-on-a-new-contract-covering-americas-west-coast-ports-transcript",
        name: "West Coast Ports Contract",
        date: "September 7, 2023",
        desc: "President Biden delivers remarks on the International Longshore and Warehouse Union (ILWU) and the Pacific Maritime Association (PMA) contract.",
      },
      {
        url: "https://www.rev.com/blog/transcripts/president-biden-delivers-remarks-reaffirming-his-commitment-to-supporting-the-people-of-florida-transcript",
        name: "Remarks to Florida Citizens",
        date: "September 3, 2023",
        desc: "President Biden visits hurricane-affected area, praises first responders, and discusses unity and disaster funding.",
      },
      {
        url: "https://www.rev.com/blog/transcripts/biden-addresses-health-care-costs-and-first-drugs-for-medicare-price-negotiations-transcript",
        name: "Medicare Price Negotiations",
        date: "August 30, 2023",
        desc: "President Biden discusses the Inflation Reduction Act, lowering drug costs, healthcare access, and economic progress.",
      },
      {
        url: "https://www.rev.com/blog/transcripts/biden-kicks-off-re-election-campaign-in-pennsylvania-transcript",
        name: "Re-Election Campaign",
        date: "June 21, 2023",
        desc: "In his re-election campaign speech to Pennsylvania, President Biden emphasizes pro-union stance, discusses economic policies, and calls for fair taxation.",
      },
    ],
  },
  williamson: {
    name: "Marianne Williamson",
    desc: "Self-help author",
    img: williamson,
    party: "Democrat",
    subheading: "Self-help author and activist",
    website: "https://marianne.com/",
    birthday: "July 8, 1952",
    about: [
      "Marianne Williamson is a self-help author, spiritual teacher, and political activist. Born on July 8, 1952, in Houston, Texas, she has gained recognition for her books and lectures on spirituality and personal growth.",
      "While not holding political office, Williamson has been an advocate for various social and political causes, including poverty reduction, healthcare reform, and environmental issues.",
      "She has also been involved in Democratic politics and ran for the Democratic nomination for the 2020 United States presidential election.",
      "Marianne Williamson's unique blend of spiritual and political perspectives has made her a notable figure in American discourse, often sparking debates and discussions.",
      "Opinions about Marianne Williamson's ideas and impact vary, with some embracing her messages of love and compassion, while others may have different views on her approach to political issues.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Marianne Williamson.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Marianne Williamson.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Marianne Williamson.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Marianne Williamson.",
      },
    ],
  },
  kennedyjr: {
    name: "Robert F. Kennedy Jr.",
    desc: "American Environmental Lawyer",
    img: kennedyJr,
    party: "Democrat",
    subheading: "Environmental advocate and lawyer",
    website: "https://www.robertfkennedyjr.com/",
    birthday: "January 17, 1954",
    about: [
      "Robert F. Kennedy Jr. is an American environmental lawyer, author, and activist. Born on January 17, 1954, in Washington, D.C., he is known for his work on environmental issues, particularly in the areas of water protection and wildlife conservation.",
      "Kennedy is a prominent advocate for clean energy and environmental sustainability. He has been involved in legal battles against polluters and has worked to raise awareness about the importance of environmental conservation.",
      "He is also a member of the Kennedy family, a well-known political dynasty in the United States, and has continued the family's tradition of public service through his environmental advocacy work.",
      "Robert F. Kennedy Jr.'s environmental efforts have garnered both praise and criticism, with supporters applauding his commitment to environmental causes and critics questioning some of his views and positions.",
      "His work has had a significant impact on the discussion of environmental policy in the United States.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Robert F. Kennedy Jr.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Robert F. Kennedy Jr.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Robert F. Kennedy Jr.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Robert F. Kennedy Jr.",
      },
    ],
  },
  trump: {
    name: "Donald Trump",
    desc: "Former President & Businessman",
    img: trump,
    party: "Republican",
    subheading: "45th President of United States",
    website: "website",
    birthday: "June 14, 1946",
    about: [
      "Donald John Trump is an American businessman, television personality, and politician who rose to prominence as the 45th President of the United States. Born on June 14, 1946, in Queens, New York City, Trump hails from a family of real estate developers. He inherited his father's real estate empire and expanded it into a global brand, becoming known for his luxurious properties, hotels, and golf courses.",
      "Trump's entrance into politics began with his announcement to run for the presidency as a Republican candidate in 2015. His unconventional and often controversial campaign style resonated with many disaffected voters, leading to his victory in the 2016 presidential election. On January 20, 2017, he was inaugurated as the 45th President of the United States. His presidency was marked by a focus on economic deregulation, tax cuts, and a more conservative approach to immigration policy.",
      "Throughout his presidency, Trump was a polarizing figure, with his policies and rhetoric often sparking heated debates and protests. He faced impeachment twice by the House of Representatives, first in 2019 on charges of abuse of power and obstruction of Congress, and again in 2021 on charges of incitement of insurrection following the storming of the U.S. Capitol by his supporters. Both times, he was acquitted by the Senate.",
      "Donald Trump's term as president ended on January 20, 2021, with the inauguration of Joe Biden. Since leaving office, Trump has remained influential within the Republican Party and has continued to be a prominent figure in American politics. His impact on American political discourse and policies has left a lasting mark on the nation, making him one of the most significant and controversial political figures in recent history.",
      "It is important to note that opinions about Donald Trump are deeply divided, with many people both supporting and opposing his policies and leadership style. This division has made him a central figure in discussions about the direction of American politics and the future of the Republican Party.",
    ],
    transcripts: [
      {
        url: "https://www.rev.com/blog/transcripts/donald-trump-speaks-to-striking-uaw-members-transcript",
        name: "Speech to UAW Members",
        date: "September 28, 2023",
        desc: "Donald Trump discusses auto industry, trade, and foreign policy in Michigan, promises to revitalize American manufacturing.",
      },
      {
        url: "https://www.rev.com/blog/transcripts/meet-the-press-full-donald-trump-interview-transcript",
        name: "Meet The Press Interview",
        date: "September 18, 2023",
        desc: "Kristen Walker interviews Donald Trump and talks about the Capitol attack, security, and potential pardons.",
      },
      {
        url: "https://www.rev.com/blog/transcripts/donald-trump-speaks-to-the-pray-vote-stand-summit-on-9-15-23-transcript",
        name: "Pray, Vote, Stand Summit",
        date: "September 18, 2023",
        desc: "Donald trump speaks about American patriots, defending freedom, faith, conservative judges, election integrity, future victory.",
      },
      {
        url: "https://www.rev.com/blog/transcripts/tucker-on-x-debate-night-interview-with-donald-trump-transcript",
        name: "X Debate Night Interview",
        date: "August 24, 2023",
        desc: "Tucker interviews Donald Trump and discusses polls, distrust in media, Bill Barr, Biden, foreign relations, election fraud, and policy plans.",
      },
    ],
  },
  haley: {
    name: "Nikki Haley",
    desc: "Former President & U.N. Ambassador",
    img: haley,
    party: "Republican",
    subheading: "Former South Carolina Governor and U.N. Ambassador",
    website: "https://www.nikkihaley.com/",
    birthday: "January 20, 1972",
    about: [
      "Nikki Haley is a prominent Republican figure who has served as the Governor of South Carolina and as the United States Ambassador to the United Nations. She was born on January 20, 1972, in Bamberg, South Carolina.",
      "Haley's political career gained national attention when she became the first female governor of South Carolina, serving from 2011 to 2017. During her tenure, she focused on economic development and job creation in the state.",
      "After her time as governor, Nikki Haley was appointed by President Donald Trump as the U.S. Ambassador to the United Nations, a role she held from 2017 to 2018. She represented the United States on the international stage and addressed global issues.",
      "Throughout her career, Haley has been a key figure in the Republican Party and has been considered a potential candidate for higher office. Her leadership style and positions on various issues have garnered both support and criticism.",
      "Nikki Haley's contributions to American politics and diplomacy continue to be subjects of discussion and debate.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Nikki Haley.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Nikki Haley.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Nikki Haley.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Nikki Haley.",
      },
    ],
  },
  ramaswamy: {
    name: "Vivek Ramaswamy",
    desc: "Entrepreneur & Author",
    img: ramaswamy,
    party: "Republican",
    subheading: "Entrepreneur and Author",
    website: "https://www.vivekramaswamy.com/",
    birthday: "August 9, 1985",
    about: [
      "Vivek Ramaswamy is a Republican entrepreneur, author, and commentator known for his work in the biotechnology and pharmaceutical industries. He was born on August 9, 1985, in Cincinnati, Ohio.",
      "Ramaswamy has made a name for himself as a biotechnology entrepreneur, founding several successful companies. He has also authored a book and is known for his conservative views on healthcare and regulatory policies.",
      "He has been a vocal advocate for a more limited government role in the pharmaceutical industry and has criticized what he sees as excessive government intervention in healthcare.",
      "Vivek Ramaswamy's unique background in biotech and his advocacy for conservative policies have made him a notable figure in the Republican Party and in discussions about healthcare and innovation.",
      "His perspectives continue to shape the conversation on these important issues in the United States.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Vivek Ramaswamy.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Vivek Ramaswamy.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Vivek Ramaswamy.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Vivek Ramaswamy.",
      },
    ],
  },
  johnson: {
    name: "Perry Johnson",
    desc: "Businessman",
    img: johnson,
    party: "Republican",
    subheading: "Businessman",
    website: "https://www.perryjohnson.com/",
    birthday: "March 3, 1960",
    about: [
      "Perry Johnson is a Republican businessman known for his entrepreneurial ventures in various industries. Born on March 3, 1960, in Houston, Texas, Johnson has built a successful career in the business world.",
      "Throughout his career, Johnson has been involved in multiple businesses, including technology startups and real estate ventures. He is recognized for his innovative approach to business and entrepreneurship.",
      "As a Republican candidate, Perry Johnson brings his business acumen and ideas to the political arena. His campaign focuses on pro-business policies, economic growth, and job creation.",
      "Perry Johnson's background in business and his advocacy for conservative economic principles have made him a notable figure in the Republican Party and the business community.",
      "His perspectives on economic issues continue to be of interest to those following Republican politics and economic policy debates.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Perry Johnson.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Perry Johnson.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Perry Johnson.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Perry Johnson.",
      },
    ],
  },

  hutchinson: {
    name: "Asa Hutchinson",
    desc: "Former Governor of Arkansas",
    img: hutchinson,
    party: "Republican",
    subheading: "Former Governor of Arkansas",
    website: "https://www.asahutchinson.com/",
    birthday: "December 3, 1950",
    about: [
      "Asa Hutchinson is a Republican politician who served as the Governor of Arkansas. Born on December 3, 1950, in Bentonville, Arkansas, he has had a long and distinguished career in public service.",
      "Hutchinson's political journey includes serving in Congress and holding various government positions before becoming the Governor of Arkansas. During his time as governor, he focused on issues such as education, healthcare, and economic development.",
      "He is known for his pragmatic approach to governance and his efforts to address challenges facing the state of Arkansas.",
      "Asa Hutchinson's contributions to Arkansas politics and his views on key issues continue to be discussed in Republican circles and in the context of state-level governance.",
      "His experience and leadership have left a lasting impact on the state of Arkansas.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Asa Hutchinson.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Asa Hutchinson.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Asa Hutchinson.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Asa Hutchinson.",
      },
    ],
  },
  elder: {
    name: "Larry Elder",
    desc: "Conservative Talk Radio Host",
    img: elder,
    party: "Republican",
    subheading: "Conservative Talk Radio Host",
    website: "https://www.larryelder.com/",
    birthday: "April 27, 1952",
    about: [
      "Larry Elder is a well-known conservative talk radio host, author, and political commentator. Born on April 27, 1952, in Los Angeles, California, he has built a successful career in media and political commentary.",
      "Elder is recognized for his conservative views and has been a prominent voice in the conservative movement. He has hosted radio and television shows where he discusses various political and social issues.",
      "As a Republican candidate, Larry Elder brings his conservative perspective to the political arena. His campaign focuses on limited government, personal responsibility, and free-market principles.",
      "Larry Elder's influential role in conservative media and his political aspirations have made him a notable figure in the Republican Party and among conservative voters.",
      "His views and commentary continue to shape conservative discourse and political discussions in the United States.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Larry Elder.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Larry Elder.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Larry Elder.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Larry Elder.",
      },
    ],
  },

  binkley: {
    name: "Ryan Binkley",
    desc: "Businessman & Pastor",
    img: binkley,
    party: "Republican",
    subheading: "Businessman and Pastor",
    website: "https://www.ryanbinkley.com/",
    birthday: "July 15, 1975",
    about: [
      "Ryan Binkley is a Republican candidate known for his background as a businessman and pastor. He was born on July 15, 1975, in Springfield, Missouri.",
      "Binkley has combined his business acumen with his commitment to faith as a pastor, leading a church congregation. His campaign emphasizes faith-based values and business-friendly policies.",
      "He is recognized for his community involvement and efforts to promote both economic growth and spiritual well-being.",
      "Ryan Binkley's unique combination of business and pastoral experience has made him a notable figure in the Republican Party and among faith-based communities.",
      "His perspectives on the intersection of faith, business, and politics continue to be of interest to voters and those following Republican politics.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Ryan Binkley.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Ryan Binkley.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Ryan Binkley.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Ryan Binkley.",
      },
    ],
  },

  tscott: {
    name: "Tim Scott",
    desc: "Senator from South Carolina",
    img: tScott,
    party: "Republican",
    subheading: "U.S. Senator from South Carolina",
    website: "https://www.timscott.com/",
    birthday: "September 19, 1965",
    about: [
      "Tim Scott is a Republican U.S. Senator representing the state of South Carolina. Born on September 19, 1965, in North Charleston, South Carolina, he has a distinguished career in public service.",
      "Scott has served in various roles, including as a member of the U.S. House of Representatives before being appointed to the U.S. Senate. He is known for his commitment to conservative principles and economic policies.",
      "Throughout his career, Senator Scott has focused on issues such as tax reform, job creation, and criminal justice reform. He has been a prominent advocate for opportunity zones as a means to revitalize distressed communities.",
      "Tim Scott's leadership in the U.S. Senate and his advocacy for conservative policies have made him a key figure in the Republican Party and in discussions about economic and social reform.",
      "His efforts to bridge divides and find common ground on important issues continue to shape the political landscape in South Carolina and the United States.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Tim Scott.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Tim Scott.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Tim Scott.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Tim Scott.",
      },
    ],
  },
  desantis: {
    name: "Ron DeSantis",
    desc: "Governor of Florida",
    img: desantis,
    party: "Republican",
    subheading: "Governor of Florida",
    website: "https://www.rondesantis.com/",
    birthday: "September 14, 1978",
    about: [
      "Ron DeSantis is a prominent Republican figure who currently serves as the Governor of Florida. Born on September 14, 1978, in Jacksonville, Florida, he has a distinguished career in politics and public service.",
      "DeSantis gained national attention for his conservative policies and leadership style during his tenure as governor. He has focused on issues such as tax cuts, education reform, and pandemic response.",
      "Throughout his career, DeSantis has advocated for limited government and conservative values. He has been a vocal supporter of Second Amendment rights and law enforcement.",
      "Ron DeSantis's leadership in Florida and his alignment with conservative principles have made him a key figure in the Republican Party and in discussions about state governance and national politics.",
      "His policies and decisions continue to be subjects of interest and debate in political circles.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Ron DeSantis.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Ron DeSantis.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Ron DeSantis.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Ron DeSantis.",
      },
    ],
  },

  pence: {
    name: "Mike Pence",
    desc: "Former Vice President",
    img: pence,
    party: "Republican",
    subheading: "Former Vice President",
    website: "https://www.mikepence.com/",
    birthday: "June 7, 1959",
    about: [
      "Mike Pence is a prominent Republican figure who served as the 48th Vice President of the United States. Born on June 7, 1959, in Columbus, Indiana, he has had a long and distinguished career in politics and public service.",
      "Pence's political journey includes serving as a member of the U.S. House of Representatives and as the Governor of Indiana before becoming Vice President. He is known for his conservative values and leadership style.",
      "Throughout his time in office, Vice President Pence played a key role in the Trump administration, focusing on issues such as tax reform, healthcare, and foreign policy.",
      "Mike Pence's role as Vice President and his alignment with conservative principles have made him a central figure in the Republican Party and in discussions about national politics and policy.",
      "His experiences in both legislative and executive roles continue to be subjects of interest and debate in political circles.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Mike Pence.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Mike Pence.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Mike Pence.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Mike Pence.",
      },
    ],
  },
  christie: {
    name: "Chris Christie",
    desc: "Former Governor of New Jersey",
    img: christie,
    party: "Republican",
    subheading: "Former Governor of New Jersey",
    website: "https://www.chrischristie.com/",
    birthday: "September 6, 1962",
    about: [
      "Chris Christie is a prominent Republican figure who served as the Governor of New Jersey. Born on September 6, 1962, in Newark, New Jersey, he has had a long and impactful career in politics.",
      "Christie's tenure as governor was marked by his handling of various crises, including Hurricane Sandy. He gained national attention for his leadership during challenging times.",
      "Throughout his career, Christie has been known for his no-nonsense approach to governance and his willingness to work across the aisle on important issues.",
      "Chris Christie's contributions to New Jersey politics and his pragmatic style of leadership have made him a key figure in the Republican Party and in discussions about effective governance.",
      "His experiences and decision-making continue to be subjects of interest and debate in political circles.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Chris Christie.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Chris Christie.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Chris Christie.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Chris Christie.",
      },
    ],
  },

  burgum: {
    name: "Doug Burgum",
    desc: "Governor of North Dakota",
    img: burgum,
    party: "Republican",
    subheading: "Governor of North Dakota",
    website: "https://www.dougburgum.com/",
    birthday: "August 1, 1956",
    about: [
      "Doug Burgum is a Republican politician who currently serves as the Governor of North Dakota. He was born on August 1, 1956, in Arthur, North Dakota.",
      "Burgum's career spans both the public and private sectors. He has been involved in the technology industry and co-founded a successful software company.",
      "As governor, Doug Burgum has prioritized issues such as economic development, technology innovation, and infrastructure improvement in North Dakota.",
      "His unique blend of technology entrepreneurship and public service has made him a notable figure in the Republican Party and in discussions about the future of North Dakota.",
      "Governor Burgum's initiatives and vision for North Dakota continue to shape the state's growth and development.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Doug Burgum.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Doug Burgum.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Doug Burgum.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Doug Burgum.",
      },
    ],
  },

  hurd: {
    name: "Will Hurd",
    desc: "Former Congressman from Texas",
    img: hurd,
    party: "Republican",
    subheading: "Former Congressman from Texas",
    website: "https://www.willhurd.com/",
    birthday: "August 19, 1977",
    about: [
      "Will Hurd is a former Republican Congressman known for his service in the U.S. House of Representatives. He was born on August 19, 1977, in San Antonio, Texas.",
      "Hurd's political career was marked by his focus on national security and technology issues. He was recognized for his expertise in cybersecurity and his efforts to address border security concerns.",
      "Throughout his time in Congress, Hurd worked across the aisle to find bipartisan solutions to complex challenges facing the United States.",
      "Will Hurd's contributions to national security and his pragmatic approach to governance have made him a respected figure in the Republican Party and in discussions about border security and technology policy.",
      "His insights and experiences continue to influence discussions on these important topics.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Will Hurd.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Will Hurd.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Will Hurd.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Will Hurd.",
      },
    ],
  },

  west: {
    name: "Cornel West",
    desc: "Professor and Progressive Activist",
    img: west,
    party: "Third Party",
    subheading: "Professor and Progressive Activist",
    website: "https://www.cornelwest.com/",
    birthday: "June 2, 1953",
    about: [
      "Cornel West is a prominent scholar, professor, and progressive activist known for his contributions to academia and social justice advocacy. He was born on June 2, 1953, in Tulsa, Oklahoma.",
      "West has a distinguished career in academia, teaching at various universities and contributing to the fields of philosophy, race studies, and ethics. He is also known for his activism and outspoken criticism of social injustices.",
      "As a third-party candidate, Cornel West brings his academic expertise and social justice advocacy to the political arena. His campaign focuses on issues such as income inequality, racial justice, and healthcare reform.",
      "Cornel West's influential role in academia and his activism have made him a notable figure in progressive circles and in discussions about social and political change.",
      "His perspectives on social justice and political reform continue to shape progressive discourse and activism in the United States.",
    ],
    transcripts: [
      {
        url: "t1url",
        name: "Transcript 1",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Cornel West.",
      },
      {
        url: "t2url",
        name: "Transcript 2",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Cornel West.",
      },
      {
        url: "t3url",
        name: "Transcript 3",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Cornel West.",
      },
      {
        url: "t4url",
        name: "Transcript 4",
        date: "September 28, 2023",
        desc: "Transcript description for a speech by Cornel West.",
      },
    ],
  },
};
